[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = true

[theme]
base = "dark"
primaryColor = "#f43f76"
backgroundColor = "#1a0b12"
secondaryBackgroundColor = "#2b101f"
textColor = "#ffffff"
font = "sans serif"

[browser]
gatherUsageStats = false
